// Dev suite server. Node built-ins only, no dependencies.
//
//   node devtools/server.js [port]     (default 8899, or just devtools)
//
// Two jobs: serve devtools/web, and be the only thing allowed to write into the
// project tree. The browser never names a path — it names a TOOL, and the
// server decides where that tool's settings live and what shape they may take.
// A compromised or buggy page therefore cannot write anywhere it likes.

import { createServer } from 'node:http';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { extname, join, resolve, dirname, normalize, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const WEB = join(HERE, 'web');
const PROJECT = resolve(HERE, '..');
// The pacing tool simulates with the REAL engine rather than a model of it —
// a model would drift from the game and the graph would quietly become
// fiction. These two read-only mounts expose it to the browser.
//
// The mount is game/js as a WHOLE, not game/js/engine: constants.js imports
// ../config/pacing-settings.js, and a mount rooted at engine/ puts that
// outside the served tree. Mirror the real layout and relative imports keep
// working unchanged.
//
// /gamejs is the graph the simulation imports — its engine/constants.js is
// swapped for a shim by an import map. /gamejs-raw is the same tree with no
// rewriting, which is how the shim (and the tool) read the real defaults.
// Both are GET-only, like every other static path.
const GAMEJS = join(PROJECT, 'game', 'js');
const PORT = Number(process.argv[2]) || 8899;

// --- what each tool is allowed to write -------------------------------------
//
// A schema entry is the whole contract: the destination, and every key with its
// type and bounds. Anything not listed is dropped, and anything out of range is
// rejected rather than clamped — a silently clamped value would be a lie about
// what you applied.

const num = (min, max) => ({ kind: 'number', min, max });
const bool = () => ({ kind: 'boolean' });
const oneOf = (...values) => ({ kind: 'enum', values });

const TOOLS = {
  pacing: {
    label: 'Pacing',
    path: 'game/js/config/pacing-settings.js',
    constName: 'PACING_SETTINGS',
    partial: true,
    doc: [
      'Pacing overrides, merged over the defaults in engine/constants.js.',
      '',
      'GENERATED by the dev suite (devtools/) — edit there and press',
      '"Apply settings to project", or edit by hand; the next apply overwrites.',
      'An empty object means "use every default".',
    ],
    schema: {
      // reveal gates: the grind each mechanic waits for
      REVEAL_TAPS_OVERCLOCK: num(1, 80),
      REVEAL_TAPS_LOOP: num(1, 120),
      REVEAL_TAPS_KV: num(1, 80),
      REVEAL_STALE_BUFFER: num(0, 100),
      REVEAL_DRAFTS_LOST: num(0, 20),
      REVEAL_COMPACTS_GOVERNOR: num(0, 20),
      // backstops: resolves after which a reveal fires regardless
      REVEAL_BACKSTOP_OVERCLOCK: num(1, 60),
      REVEAL_BACKSTOP_KV: num(1, 60),
      REVEAL_BACKSTOP_BUFFER: num(1, 60),
      REVEAL_BACKSTOP_DRAFTCAP: num(1, 60),
      REVEAL_BACKSTOP_LOOP: num(1, 60),
      REVEAL_BACKSTOP_GOVERNOR: num(1, 80),
      // arrival cadence
      ARRIVAL_BASE_TICKS: num(10, 300),
      READ_TICKS_PER_CHAR: num(0, 1),
      READ_TICKS_MAX: num(0, 200),
      // buffer economy
      STALE_PER_TOKEN: num(0.05, 5),
      STALE_SOFT_KNEE: num(0, 99),
      COMPACT_TICKS: num(1, 100),
      COMPACT_FACTOR: num(0.01, 0.99),
      FLUSH_COST_CYCLES: num(0, 10),
      GOVERNOR_TRIGGER: num(10, 100),
      // unlock economy
      LOOP_UNLOCK_CYCLES: num(1, 60),
      TOOL_UNLOCK_CYCLES: num(1, 80),
      DRAFT_CAP_UNLOCK_RESOLVES: num(1, 40),
      OVERCLOCK_UNLOCK_RESOLVES: num(1, 40),
      // era length
      ERA3_BEFORE_DEVOPS: num(1, 60),
    },
  },
  diffusion: {
    label: 'Diffusion text',
    path: 'game/js/config/diffusion-settings.js',
    constName: 'DIFFUSION_SETTINGS',
    doc: [
      'Answer diffusion settings.',
      '',
      'GENERATED by the dev suite (devtools/) — edit there and press',
      '"Apply settings to project", or edit by hand; the next apply overwrites.',
      'See docs/superpowers/specs/2026-08-07-answer-diffusion-design.md.',
    ],
    schema: {
      scheduler: oneOf('uniform', 'stochastic', 'wavefront', 'spans'),
      shimmerMode: oneOf('fixed', 'relative'),
      shimmerHz: num(1, 120),
      shimmerPerToken: num(0.05, 20),
      shimmerFloorHz: num(1, 120),
      gamma: num(0.1, 10),
      lockBase: num(0, 1),
      delta: num(0.1, 10),
      unsettle: num(0, 1),
      spread: num(0, 0.99),
      bias: num(0, 1),
      spanJitter: num(0, 2),
      preserveClass: bool(),
      blockNoise: bool(),
      glyphNoise: bool(),
      lumJitter: num(0, 1),
      flashStrength: num(0, 4),
      flashHoldMs: num(0, 5000),
      flashFadeMs: num(0, 5000),
    },
  },
};

// `partial` tools may omit keys: their generated module is an OVERRIDE layer
// merged over the engine's defaults, so writing every key would pin today's
// defaults forever and silently hold the old value the next time one moved.
function validate(schema, input, partial = false) {
  const out = {};
  const errors = [];
  for (const [key, rule] of Object.entries(schema)) {
    if (!(key in input)) {
      if (!partial) errors.push(`missing ${key}`);
      continue;
    }
    const v = input[key];
    if (rule.kind === 'number') {
      if (typeof v !== 'number' || !Number.isFinite(v)) errors.push(`${key} must be a finite number`);
      else if (v < rule.min || v > rule.max) errors.push(`${key} must be within ${rule.min}..${rule.max} (got ${v})`);
      else out[key] = v;
    } else if (rule.kind === 'boolean') {
      if (typeof v !== 'boolean') errors.push(`${key} must be a boolean`);
      else out[key] = v;
    } else if (rule.kind === 'enum') {
      if (!rule.values.includes(v)) errors.push(`${key} must be one of ${rule.values.join(', ')}`);
      else out[key] = v;
    }
  }
  const extra = Object.keys(input).filter((k) => !(k in schema));
  if (extra.length) errors.push(`unknown keys: ${extra.join(', ')}`);
  return { value: out, errors };
}

function renderModule(tool, settings) {
  const doc = tool.doc.map((line) => (line ? `// ${line}` : '//')).join('\n');
  const body = Object.entries(settings)
    .map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`)
    .join('\n');
  return `${doc}\n\nexport const ${tool.constName} = Object.freeze({\n${body}\n});\n`;
}

// --- static file serving ----------------------------------------------------

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.md': 'text/plain; charset=utf-8',
};

async function serveStatic(req, res, pathname) {
  const rel = normalize(decodeURIComponent(pathname)).replace(/^([/\\])+/, '');
  const full = join(WEB, rel === '' ? 'index.html' : rel);
  // normalize() has already collapsed any ..; this is the belt to that braces.
  if (!full.startsWith(WEB + sep) && full !== join(WEB, 'index.html')) {
    return send(res, 403, { error: 'forbidden' });
  }
  try {
    const body = await readFile(full);
    res.writeHead(200, {
      'content-type': TYPES[extname(full)] || 'application/octet-stream',
      'cache-control': 'no-store', // this is a dev tool; never serve a stale module
    });
    res.end(body);
  } catch {
    send(res, 404, { error: `not found: /${rel}` });
  }
}

// Serve one file out of `base`, with the same traversal guard as serveStatic.
async function serveFrom(res, base, rel) {
  const full = join(base, normalize(decodeURIComponent(rel)).replace(/^([/\\])+/, ''));
  if (!full.startsWith(base + sep)) return send(res, 403, { error: 'forbidden' });
  try {
    res.writeHead(200, {
      'content-type': TYPES[extname(full)] || 'application/octet-stream',
      'cache-control': 'no-store',
    });
    res.end(await readFile(full));
  } catch {
    send(res, 404, { error: `not found: ${rel}` });
  }
}

function send(res, code, obj) {
  const body = JSON.stringify(obj);
  res.writeHead(code, { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' });
  res.end(body);
}

function readBody(req, limit = 64 * 1024) {
  return new Promise((ok, fail) => {
    let size = 0;
    const chunks = [];
    req.on('data', (c) => {
      size += c.length;
      if (size > limit) {
        fail(new Error('body too large'));
        req.destroy();
        return;
      }
      chunks.push(c);
    });
    req.on('end', () => ok(Buffer.concat(chunks).toString('utf8')));
    req.on('error', fail);
  });
}

// --- routes -----------------------------------------------------------------

async function handleApply(req, res) {
  let payload;
  try {
    payload = JSON.parse(await readBody(req));
  } catch (err) {
    return send(res, 400, { error: `bad request body: ${err.message}` });
  }

  const tool = TOOLS[payload?.tool];
  if (!tool) return send(res, 404, { error: `unknown tool: ${payload?.tool}` });
  if (!payload.settings || typeof payload.settings !== 'object') {
    return send(res, 400, { error: 'settings must be an object' });
  }

  const { value, errors } = validate(tool.schema, payload.settings, tool.partial === true);
  if (errors.length) return send(res, 422, { error: `rejected: ${errors.join('; ')}` });

  const dest = join(PROJECT, tool.path);
  const text = renderModule(tool, value);

  let previous = null;
  try {
    previous = await readFile(dest, 'utf8');
  } catch { /* first write */ }

  if (previous === text) {
    return send(res, 200, { path: tool.path, changed: false });
  }

  try {
    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, text, 'utf8');
  } catch (err) {
    return send(res, 500, { error: `write failed: ${err.message}` });
  }

  console.log(`[apply] ${tool.path} <- ${payload.tool} (${previous === null ? 'created' : 'updated'})`);
  send(res, 200, { path: tool.path, changed: true, created: previous === null });
}

const server = createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  const path = url.pathname;

  if (path === '/api/health') {
    return send(res, 200, { ok: true, project: PROJECT, tools: Object.keys(TOOLS) });
  }

  if (path.startsWith('/api/target/')) {
    const tool = TOOLS[decodeURIComponent(path.slice('/api/target/'.length))];
    if (!tool) return send(res, 404, { error: 'unknown tool' });
    return send(res, 200, { path: tool.path, exists: existsSync(join(PROJECT, tool.path)) });
  }

  if (path === '/api/apply') {
    if (req.method !== 'POST') return send(res, 405, { error: 'POST only' });
    return handleApply(req, res);
  }

  if (req.method !== 'GET' && req.method !== 'HEAD') return send(res, 405, { error: 'GET only' });
  // Read-only engine mounts. See the ENGINE comment at the top.
  if (path.startsWith('/gamejs-raw/')) {
    return serveFrom(res, GAMEJS, path.slice('/gamejs-raw/'.length));
  }
  if (path.startsWith('/gamejs/')) {
    return serveFrom(res, GAMEJS, path.slice('/gamejs/'.length));
  }
  return serveStatic(req, res, path);
});

// Loopback only. This process writes to the working tree; it has no business
// being reachable from the network.
server.listen(PORT, '127.0.0.1', () => {
  console.log(`dev suite  http://localhost:${PORT}`);
  console.log(`project    ${PROJECT}`);
});
