// Dev suite server. Node built-ins only, no dependencies.
//
//   node devtools/server.js [port]     (default 8899, or just devtools)
//
// Two jobs: serve devtools/web, and be the only thing allowed to write into the
// project tree. The browser never names a path — it names a TOOL, and the
// server decides where that tool's settings live and what shape they may take.
// A compromised or buggy page therefore cannot write anywhere it likes.

import { createServer } from 'node:http';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { extname, join, resolve, dirname, normalize, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const WEB = join(HERE, 'web');
const PROJECT = resolve(HERE, '..');
const PORT = Number(process.argv[2]) || 8899;

// --- what each tool is allowed to write -------------------------------------
//
// A schema entry is the whole contract: the destination, and every key with its
// type and bounds. Anything not listed is dropped, and anything out of range is
// rejected rather than clamped — a silently clamped value would be a lie about
// what you applied.

const num = (min, max) => ({ kind: 'number', min, max });
const bool = () => ({ kind: 'boolean' });
const oneOf = (...values) => ({ kind: 'enum', values });

const TOOLS = {
  diffusion: {
    label: 'Diffusion text',
    path: 'game/js/config/diffusion-settings.js',
    constName: 'DIFFUSION_SETTINGS',
    doc: [
      'Answer diffusion settings.',
      '',
      'GENERATED by the dev suite (devtools/) — edit there and press',
      '"Apply settings to project", or edit by hand; the next apply overwrites.',
      'See docs/superpowers/specs/2026-08-07-answer-diffusion-design.md.',
    ],
    schema: {
      scheduler: oneOf('uniform', 'stochastic', 'wavefront', 'spans'),
      shimmerMode: oneOf('fixed', 'relative'),
      shimmerHz: num(1, 120),
      shimmerPerToken: num(0.05, 20),
      shimmerFloorHz: num(1, 120),
      gamma: num(0.1, 10),
      lockBase: num(0, 1),
      delta: num(0.1, 10),
      unsettle: num(0, 1),
      spread: num(0, 0.99),
      bias: num(0, 1),
      spanJitter: num(0, 2),
      preserveClass: bool(),
      blockNoise: bool(),
      glyphNoise: bool(),
      lumJitter: num(0, 1),
      flashStrength: num(0, 4),
      flashHoldMs: num(0, 5000),
      flashFadeMs: num(0, 5000),
    },
  },
};

function validate(schema, input) {
  const out = {};
  const errors = [];
  for (const [key, rule] of Object.entries(schema)) {
    if (!(key in input)) {
      errors.push(`missing ${key}`);
      continue;
    }
    const v = input[key];
    if (rule.kind === 'number') {
      if (typeof v !== 'number' || !Number.isFinite(v)) errors.push(`${key} must be a finite number`);
      else if (v < rule.min || v > rule.max) errors.push(`${key} must be within ${rule.min}..${rule.max} (got ${v})`);
      else out[key] = v;
    } else if (rule.kind === 'boolean') {
      if (typeof v !== 'boolean') errors.push(`${key} must be a boolean`);
      else out[key] = v;
    } else if (rule.kind === 'enum') {
      if (!rule.values.includes(v)) errors.push(`${key} must be one of ${rule.values.join(', ')}`);
      else out[key] = v;
    }
  }
  const extra = Object.keys(input).filter((k) => !(k in schema));
  if (extra.length) errors.push(`unknown keys: ${extra.join(', ')}`);
  return { value: out, errors };
}

function renderModule(tool, settings) {
  const doc = tool.doc.map((line) => (line ? `// ${line}` : '//')).join('\n');
  const body = Object.entries(settings)
    .map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`)
    .join('\n');
  return `${doc}\n\nexport const ${tool.constName} = Object.freeze({\n${body}\n});\n`;
}

// --- static file serving ----------------------------------------------------

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.md': 'text/plain; charset=utf-8',
};

async function serveStatic(req, res, pathname) {
  const rel = normalize(decodeURIComponent(pathname)).replace(/^([/\\])+/, '');
  const full = join(WEB, rel === '' ? 'index.html' : rel);
  // normalize() has already collapsed any ..; this is the belt to that braces.
  if (!full.startsWith(WEB + sep) && full !== join(WEB, 'index.html')) {
    return send(res, 403, { error: 'forbidden' });
  }
  try {
    const body = await readFile(full);
    res.writeHead(200, {
      'content-type': TYPES[extname(full)] || 'application/octet-stream',
      'cache-control': 'no-store', // this is a dev tool; never serve a stale module
    });
    res.end(body);
  } catch {
    send(res, 404, { error: `not found: /${rel}` });
  }
}

function send(res, code, obj) {
  const body = JSON.stringify(obj);
  res.writeHead(code, { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' });
  res.end(body);
}

function readBody(req, limit = 64 * 1024) {
  return new Promise((ok, fail) => {
    let size = 0;
    const chunks = [];
    req.on('data', (c) => {
      size += c.length;
      if (size > limit) {
        fail(new Error('body too large'));
        req.destroy();
        return;
      }
      chunks.push(c);
    });
    req.on('end', () => ok(Buffer.concat(chunks).toString('utf8')));
    req.on('error', fail);
  });
}

// --- routes -----------------------------------------------------------------

async function handleApply(req, res) {
  let payload;
  try {
    payload = JSON.parse(await readBody(req));
  } catch (err) {
    return send(res, 400, { error: `bad request body: ${err.message}` });
  }

  const tool = TOOLS[payload?.tool];
  if (!tool) return send(res, 404, { error: `unknown tool: ${payload?.tool}` });
  if (!payload.settings || typeof payload.settings !== 'object') {
    return send(res, 400, { error: 'settings must be an object' });
  }

  const { value, errors } = validate(tool.schema, payload.settings);
  if (errors.length) return send(res, 422, { error: `rejected: ${errors.join('; ')}` });

  const dest = join(PROJECT, tool.path);
  const text = renderModule(tool, value);

  let previous = null;
  try {
    previous = await readFile(dest, 'utf8');
  } catch { /* first write */ }

  if (previous === text) {
    return send(res, 200, { path: tool.path, changed: false });
  }

  try {
    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, text, 'utf8');
  } catch (err) {
    return send(res, 500, { error: `write failed: ${err.message}` });
  }

  console.log(`[apply] ${tool.path} <- ${payload.tool} (${previous === null ? 'created' : 'updated'})`);
  send(res, 200, { path: tool.path, changed: true, created: previous === null });
}

const server = createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  const path = url.pathname;

  if (path === '/api/health') {
    return send(res, 200, { ok: true, project: PROJECT, tools: Object.keys(TOOLS) });
  }

  if (path.startsWith('/api/target/')) {
    const tool = TOOLS[decodeURIComponent(path.slice('/api/target/'.length))];
    if (!tool) return send(res, 404, { error: 'unknown tool' });
    return send(res, 200, { path: tool.path, exists: existsSync(join(PROJECT, tool.path)) });
  }

  if (path === '/api/apply') {
    if (req.method !== 'POST') return send(res, 405, { error: 'POST only' });
    return handleApply(req, res);
  }

  if (req.method !== 'GET' && req.method !== 'HEAD') return send(res, 405, { error: 'GET only' });
  return serveStatic(req, res, path);
});

// Loopback only. This process writes to the working tree; it has no business
// being reachable from the network.
server.listen(PORT, '127.0.0.1', () => {
  console.log(`dev suite  http://localhost:${PORT}`);
  console.log(`project    ${PROJECT}`);
});
